const ASTEROID_ANGLE_RANGE = 80;
const ASTEROID_START = 1000;
const ASTEROID_RING_WIDTH = 130;
const ASTEROID_RINGS = 6;
const ASTEROIDS_PER_RING = 5;
const ASTEROID_SPACE = ASTEROID_START + ASTEROID_RING_WIDTH * ASTEROID_RINGS;